// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx41jVuo6KhbsnJMUFJuhHHlTIlezkKxc',
    appId: '1:973154739087:web:f851bec90044e6119fa1fa',
    messagingSenderId: '973154739087',
    projectId: 'photoshare-3bb64',
    authDomain: 'photoshare-3bb64.firebaseapp.com',
    storageBucket: 'photoshare-3bb64.firebasestorage.app',
    measurementId: 'G-CGKQETVR2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ZrlLjsr9SdfyGT5_Yc4qlSCUCQX8EsY',
    appId: '1:973154739087:android:da693e7dea60efd09fa1fa',
    messagingSenderId: '973154739087',
    projectId: 'photoshare-3bb64',
    storageBucket: 'photoshare-3bb64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURiJOCJf0qZlwiI56wDVUXLwth786_dQ',
    appId: '1:973154739087:ios:570cd05a067246a69fa1fa',
    messagingSenderId: '973154739087',
    projectId: 'photoshare-3bb64',
    storageBucket: 'photoshare-3bb64.firebasestorage.app',
    iosBundleId: 'com.example.photoShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURiJOCJf0qZlwiI56wDVUXLwth786_dQ',
    appId: '1:973154739087:ios:570cd05a067246a69fa1fa',
    messagingSenderId: '973154739087',
    projectId: 'photoshare-3bb64',
    storageBucket: 'photoshare-3bb64.firebasestorage.app',
    iosBundleId: 'com.example.photoShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx41jVuo6KhbsnJMUFJuhHHlTIlezkKxc',
    appId: '1:973154739087:web:af74cd2d702dec5d9fa1fa',
    messagingSenderId: '973154739087',
    projectId: 'photoshare-3bb64',
    authDomain: 'photoshare-3bb64.firebaseapp.com',
    storageBucket: 'photoshare-3bb64.firebasestorage.app',
    measurementId: 'G-458TQ6810K',
  );
}
