// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXX7S5cxeAfpsLtiB1NZ9Nh0vdo6MmyM',
    appId: '1:343027934013:web:a81c67cee318577b5e1b54',
    messagingSenderId: '343027934013',
    projectId: 'minimal-ace65',
    authDomain: 'minimal-ace65.firebaseapp.com',
    storageBucket: 'minimal-ace65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhDwa5Nmret00nCTRLIT4Layi6bYMnYo',
    appId: '1:343027934013:android:7e6e97cea6c921cb5e1b54',
    messagingSenderId: '343027934013',
    projectId: 'minimal-ace65',
    storageBucket: 'minimal-ace65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlLUeqa8wq8-wkBmRtO5qk4FUQt8lpK4',
    appId: '1:343027934013:ios:0f62174736efd01c5e1b54',
    messagingSenderId: '343027934013',
    projectId: 'minimal-ace65',
    storageBucket: 'minimal-ace65.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlLUeqa8wq8-wkBmRtO5qk4FUQt8lpK4',
    appId: '1:343027934013:ios:0f62174736efd01c5e1b54',
    messagingSenderId: '343027934013',
    projectId: 'minimal-ace65',
    storageBucket: 'minimal-ace65.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXX7S5cxeAfpsLtiB1NZ9Nh0vdo6MmyM',
    appId: '1:343027934013:web:0b330c24d7ec53a15e1b54',
    messagingSenderId: '343027934013',
    projectId: 'minimal-ace65',
    authDomain: 'minimal-ace65.firebaseapp.com',
    storageBucket: 'minimal-ace65.firebasestorage.app',
  );
}
